import type { StrategyDefinition } from "./contracts.ts";
import { runSmartMoneyConcepts } from "./smartMoneyConcepts.ts";
import { BLUE, GREEN, RED } from "./smartMoneyConceptsParameters.ts";

export function createSmartMoneyConceptsStrategyDefinition(): StrategyDefinition {
  const strategy: StrategyDefinition = {
    key: "smart-money-concepts",
    name: "Smart Money Concepts [LuxAlgo]",
    version: "1.0.0",
    description:
      "确定性复刻 LuxAlgo Smart Money Concepts：内部/摆动结构、订单块、EQH/EQL、FVG、多周期高低点与溢价/均衡/折价区域。",
    sourceType: "preset",
    sourceFile: "trading-strategies/Smart Money Concepts.md",
    strategyType: "indicator",
    defaultEnabled: false,
    supportedMarkets: ["CN", "HK", "US"],
    supportedTimeframes: ["realtime", "1m", "5m", "15m", "30m", "1h", "1d", "1w"],
    parameterSchema: [
      {
        key: "mode",
        label: "显示模式",
        type: "select",
        defaultValue: "historical",
        options: [
          { label: "Historical", value: "historical" },
          { label: "Present", value: "present" },
        ],
      },
      {
        key: "style",
        label: "颜色样式",
        type: "select",
        defaultValue: "colored",
        options: [
          { label: "Colored", value: "colored" },
          { label: "Monochrome", value: "monochrome" },
        ],
      },
      { key: "showTrendCandles", label: "按趋势着色蜡烛", type: "boolean", defaultValue: false },
      { key: "showInternalStructure", label: "内部结构", type: "boolean", defaultValue: true },
      {
        key: "internalBullishDisplay",
        label: "内部看涨结构",
        type: "select",
        defaultValue: "all",
        options: [
          { label: "All", value: "all" },
          { label: "BOS", value: "bos" },
          { label: "CHoCH", value: "choch" },
        ],
      },
      {
        key: "internalBearishDisplay",
        label: "内部看跌结构",
        type: "select",
        defaultValue: "all",
        options: [
          { label: "All", value: "all" },
          { label: "BOS", value: "bos" },
          { label: "CHoCH", value: "choch" },
        ],
      },
      {
        key: "internalConfluenceFilter",
        label: "内部结构 Confluence Filter",
        type: "boolean",
        defaultValue: false,
      },
      {
        key: "internalStructureTextSize",
        label: "内部结构标签大小",
        type: "select",
        defaultValue: "tiny",
        options: [
          { label: "Tiny", value: "tiny" },
          { label: "Small", value: "small" },
          { label: "Normal", value: "normal" },
        ],
      },
      { key: "showSwingStructure", label: "摆动结构", type: "boolean", defaultValue: true },
      {
        key: "swingBullishDisplay",
        label: "摆动看涨结构",
        type: "select",
        defaultValue: "all",
        options: [
          { label: "All", value: "all" },
          { label: "BOS", value: "bos" },
          { label: "CHoCH", value: "choch" },
        ],
      },
      {
        key: "swingBearishDisplay",
        label: "摆动看跌结构",
        type: "select",
        defaultValue: "all",
        options: [
          { label: "All", value: "all" },
          { label: "BOS", value: "bos" },
          { label: "CHoCH", value: "choch" },
        ],
      },
      {
        key: "swingStructureTextSize",
        label: "摆动结构标签大小",
        type: "select",
        defaultValue: "small",
        options: [
          { label: "Tiny", value: "tiny" },
          { label: "Small", value: "small" },
          { label: "Normal", value: "normal" },
        ],
      },
      { key: "showSwingPoints", label: "HH / HL / LH / LL", type: "boolean", defaultValue: false },
      {
        key: "showStrongWeakHighLow",
        label: "Strong / Weak High / Low",
        type: "boolean",
        defaultValue: true,
      },
      { key: "swingLength", label: "摆动枢轴长度", type: "number", defaultValue: 50 },
      { key: "showInternalOrderBlocks", label: "内部订单块", type: "boolean", defaultValue: true },
      { key: "internalOrderBlockCount", label: "内部订单块数量", type: "number", defaultValue: 5 },
      { key: "showSwingOrderBlocks", label: "摆动订单块", type: "boolean", defaultValue: false },
      { key: "swingOrderBlockCount", label: "摆动订单块数量", type: "number", defaultValue: 5 },
      {
        key: "orderBlockFilter",
        label: "订单块波动过滤",
        type: "select",
        defaultValue: "atr",
        options: [
          { label: "ATR (200)", value: "atr" },
          { label: "Cumulative Mean Range", value: "cumulative-mean-range" },
        ],
      },
      {
        key: "orderBlockMitigation",
        label: "订单块失效来源",
        type: "select",
        defaultValue: "high-low",
        options: [
          { label: "High / Low", value: "high-low" },
          { label: "Close", value: "close" },
        ],
      },
      { key: "showEqualHighLow", label: "EQH / EQL", type: "boolean", defaultValue: true },
      { key: "equalHighLowLength", label: "EQH / EQL 确认长度", type: "number", defaultValue: 3 },
      { key: "equalHighLowThreshold", label: "EQH / EQL 阈值", type: "number", defaultValue: 0.1 },
      {
        key: "equalHighLowTextSize",
        label: "EQH / EQL 标签大小",
        type: "select",
        defaultValue: "tiny",
        options: [
          { label: "Tiny", value: "tiny" },
          { label: "Small", value: "small" },
          { label: "Normal", value: "normal" },
        ],
      },
      { key: "showFairValueGaps", label: "Fair Value Gaps", type: "boolean", defaultValue: false },
      {
        key: "fairValueGapAutoThreshold",
        label: "FVG 自动阈值",
        type: "boolean",
        defaultValue: true,
      },
      {
        key: "fairValueGapTimeframe",
        label: "FVG 周期",
        type: "select",
        defaultValue: "current",
        options: [
          { label: "当前周期", value: "current" },
          { label: "5m", value: "5m" },
          { label: "15m", value: "15m" },
          { label: "30m", value: "30m" },
          { label: "1h", value: "1h" },
          { label: "1d", value: "1d" },
          { label: "1w", value: "1w" },
        ],
      },
      { key: "fairValueGapExtend", label: "FVG 右侧延伸", type: "number", defaultValue: 1 },
      { key: "showDailyLevels", label: "前日高低点", type: "boolean", defaultValue: false },
      {
        key: "dailyLevelsStyle",
        label: "前日高低点线型",
        type: "select",
        defaultValue: "solid",
        options: [
          { label: "Solid", value: "solid" },
          { label: "Dashed", value: "dashed" },
          { label: "Dotted", value: "dotted" },
        ],
      },
      { key: "showWeeklyLevels", label: "前周高低点", type: "boolean", defaultValue: false },
      {
        key: "weeklyLevelsStyle",
        label: "前周高低点线型",
        type: "select",
        defaultValue: "solid",
        options: [
          { label: "Solid", value: "solid" },
          { label: "Dashed", value: "dashed" },
          { label: "Dotted", value: "dotted" },
        ],
      },
      { key: "showMonthlyLevels", label: "前月高低点", type: "boolean", defaultValue: false },
      {
        key: "monthlyLevelsStyle",
        label: "前月高低点线型",
        type: "select",
        defaultValue: "solid",
        options: [
          { label: "Solid", value: "solid" },
          { label: "Dashed", value: "dashed" },
          { label: "Dotted", value: "dotted" },
        ],
      },
      {
        key: "showPremiumDiscountZones",
        label: "Premium / Equilibrium / Discount",
        type: "boolean",
        defaultValue: false,
      },
      {
        key: "internalBullishColor",
        label: "内部看涨结构颜色",
        type: "color",
        defaultValue: GREEN,
      },
      { key: "internalBearishColor", label: "内部看跌结构颜色", type: "color", defaultValue: RED },
      { key: "swingBullishColor", label: "摆动看涨结构颜色", type: "color", defaultValue: GREEN },
      { key: "swingBearishColor", label: "摆动看跌结构颜色", type: "color", defaultValue: RED },
      {
        key: "internalBullishOrderBlockColor",
        label: "内部看涨订单块",
        type: "color",
        defaultValue: "#3179F5",
      },
      {
        key: "internalBearishOrderBlockColor",
        label: "内部看跌订单块",
        type: "color",
        defaultValue: "#F77C80",
      },
      {
        key: "swingBullishOrderBlockColor",
        label: "摆动看涨订单块",
        type: "color",
        defaultValue: "#1848CC",
      },
      {
        key: "swingBearishOrderBlockColor",
        label: "摆动看跌订单块",
        type: "color",
        defaultValue: "#B22833",
      },
      {
        key: "bullishFairValueGapColor",
        label: "看涨 FVG",
        type: "color",
        defaultValue: "#00FF68",
      },
      {
        key: "bearishFairValueGapColor",
        label: "看跌 FVG",
        type: "color",
        defaultValue: "#FF0008",
      },
      { key: "dailyLevelsColor", label: "前日高低点颜色", type: "color", defaultValue: BLUE },
      { key: "weeklyLevelsColor", label: "前周高低点颜色", type: "color", defaultValue: BLUE },
      { key: "monthlyLevelsColor", label: "前月高低点颜色", type: "color", defaultValue: BLUE },
      { key: "premiumZoneColor", label: "Premium Zone", type: "color", defaultValue: RED },
      {
        key: "equilibriumZoneColor",
        label: "Equilibrium Zone",
        type: "color",
        defaultValue: "#878B94",
      },
      { key: "discountZoneColor", label: "Discount Zone", type: "color", defaultValue: GREEN },
    ],
    run: (input) => runSmartMoneyConcepts(strategy, input),
  };

  return strategy;
}
